import type { EditorialPublication } from "./types";

const now = "2026-08-30T10:00:00.000Z";

export const editorialSeed: EditorialPublication[] = [
  {
    id: "tropicoul-au-marche-de-bamako",
    slug: "tropicoul-au-marche-de-bamako",
    type: "activity",
    brand: "Tropicoul",
    status: "published",
    title: "Tropicoul apporte une note fruitée au marché de Bamako",
    excerpt: "Une journée de dégustation, de rencontres et de fraîcheur autour de nos saveurs Tropicoul.",
    body: "Des premières dégustations aux discussions spontanées, cette activation a réuni les amateurs de boissons fruitées autour de la gamme Tropicoul. Ananas, Mangue, Orange, Goyave, Cocktail et Tamarin ont accompagné les échanges tout au long de la journée.\n\nNous remercions toutes les personnes venues découvrir les canettes et partager leurs impressions. Cette énergie de proximité nourrit chaque nouvelle rencontre Multiproduit Mali.",
    coverImage: "/media/mpm/universes/tropicoul-goyave/goyave-lifestyle-mid-v01.webp",
    gallery: [
      "/media/mpm/universes/tropicoul-goyave/goyave-lifestyle-mid-v01.webp",
      "/media/mpm/universes/tropicoul-ananas/ananas-lifestyle-mid-v01.webp",
    ],
    location: "Bamako, Mali",
    startsAt: "2026-08-22T09:00:00.000Z",
    endsAt: "2026-08-22T18:00:00.000Z",
    publishedAt: "2026-08-25T09:00:00.000Z",
    scheduledAt: null,
    isFeatured: true,
    commentsEnabled: true,
    commentCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "rendez-vous-saveurs-de-bamako",
    slug: "rendez-vous-saveurs-de-bamako",
    type: "event",
    brand: "Multiproduit Mali",
    status: "published",
    title: "Rendez-vous Saveurs de Bamako : retrouvons-nous le 19 septembre",
    excerpt: "Un moment ouvert à toutes et tous pour découvrir, déguster et échanger autour de nos marques.",
    body: "Multiproduit Mali vous donne rendez-vous pour un après-midi de dégustations et de découvertes. Tropicoul, Triplex et Vimto Sparkling seront réunis dans un même espace pour faire vivre leurs univers respectifs.\n\nL'entrée est libre. Venez avec vos questions, vos envies et votre curiosité : notre équipe sera là pour vous accueillir.",
    coverImage: "/media/mpm/universes/tropicoul-ananas/ananas-lifestyle-mid-v01.webp",
    gallery: ["/media/mpm/universes/tropicoul-ananas/ananas-lifestyle-mid-v01.webp"],
    location: "Palais de la Culture, Bamako",
    startsAt: "2026-09-19T15:00:00.000Z",
    endsAt: "2026-09-19T20:00:00.000Z",
    publishedAt: "2026-08-29T09:00:00.000Z",
    scheduledAt: null,
    isFeatured: false,
    commentsEnabled: true,
    commentCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "triplex-au-coeur-des-journees-intenses",
    slug: "triplex-au-coeur-des-journees-intenses",
    type: "activity",
    brand: "Triplex",
    status: "published",
    title: "Triplex au cœur des journées qui gardent le rythme",
    excerpt: "Une présence affirmée au plus près de celles et ceux qui avancent sans ralentir.",
    body: "Triplex Energy Drink accompagne les moments où le rythme s'accélère. Au fil de cette activation, les visiteurs ont découvert son identité intense et sa canette au caractère franc.\n\nLa rencontre a surtout permis de recueillir des retours directs sur le goût, l'univers de la marque et les moments où Triplex trouve naturellement sa place.",
    coverImage: "/media/mpm/product-pages/triplex-original/images/triplex-original__hero-desktop__1280w.webp",
    gallery: ["/media/mpm/universes/triplex-original/triplex-lifestyle-mid-v01.webp"],
    location: "Bamako, Mali",
    startsAt: "2026-08-14T10:00:00.000Z",
    endsAt: "2026-08-14T18:00:00.000Z",
    publishedAt: "2026-08-18T09:00:00.000Z",
    scheduledAt: null,
    isFeatured: false,
    commentsEnabled: true,
    commentCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "vimto-sparkling-moments-partages",
    slug: "vimto-sparkling-moments-partages",
    type: "partnership",
    brand: "Vimto",
    status: "published",
    title: "Vimto Sparkling s'invite dans les moments partagés",
    excerpt: "Une boisson fruitée pétillante pensée pour mettre de la couleur et du goût à table.",
    body: "Vimto Sparkling est arrivé au Mali avec son identité rouge, blanche et jaune reconnaissable entre toutes. Son goût fruité et pétillant accompagne naturellement les repas, les retrouvailles et les pauses qui méritent un peu plus de caractère.\n\nCette première prise de parole ouvre une série de rencontres avec les distributeurs, les restaurateurs et le public.",
    coverImage: "/media/mpm/product-pages/vimto-sparkling/v2/hero-desktop.webp",
    gallery: [
      "/media/mpm/product-pages/vimto-sparkling/v2/hero-desktop.webp",
      "/media/mpm/universes/vimto-sparkling/vimto-editorial-lifestyle-v03.webp",
    ],
    location: "Bamako, Mali",
    startsAt: "2026-08-05T10:00:00.000Z",
    endsAt: null,
    publishedAt: "2026-08-09T09:00:00.000Z",
    scheduledAt: null,
    isFeatured: false,
    commentsEnabled: true,
    commentCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "retour-sur-la-degustation-tropicoul-ananas",
    slug: "retour-sur-la-degustation-tropicoul-ananas",
    type: "event",
    brand: "Tropicoul",
    status: "archived",
    title: "Retour en images sur la dégustation Tropicoul Ananas",
    excerpt: "Une galerie de moments solaires, de dégustations fraîches et de conversations spontanées.",
    body: "Cette dégustation a permis de faire découvrir Tropicoul Ananas dans une ambiance ouverte et chaleureuse. Retrouvez ici quelques images de la journée et les premiers retours de la communauté.",
    coverImage: "/media/mpm/product-pages/tropicoul-ananas/images/tropicoul-ananas__hero-desktop__1280w.webp",
    gallery: [
      "/media/mpm/product-pages/tropicoul-ananas/images/tropicoul-ananas__hero-desktop__1280w.webp",
      "/media/mpm/universes/tropicoul-ananas/ananas-lifestyle-mid-v01.webp",
    ],
    location: "Bamako, Mali",
    startsAt: "2026-07-12T10:00:00.000Z",
    endsAt: "2026-07-12T17:00:00.000Z",
    publishedAt: "2026-07-15T09:00:00.000Z",
    scheduledAt: null,
    isFeatured: false,
    commentsEnabled: true,
    commentCount: 0,
    createdAt: now,
    updatedAt: now,
  },
];
