export type ProductUniverseStory = {
  id: string;
  order: number;
  eyebrow: string;
  title: string;
  body: string;
  alt: string;
  layout: string;
  animation: string;
  src: string;
  avif: string;
  width: number;
  height: number;
};

export const PRODUCT_UNIVERSE_STORIES = {
  "triplex-original": [
    {
      "id": "triplex-original-01",
      "order": 1,
      "eyebrow": "Aux origines",
      "title": "Avant l’aube",
      "body": "L’élan commence avant le bruit.",
      "alt": "Triplex Original — avant l’aube, photographie éditoriale.",
      "layout": "full-bleed",
      "animation": "parallax-soft",
      "src": "/media/mpm/editorial/triplex-original/triplex-original-univers-01-triplex-original-univers-01-source.webp",
      "avif": "/media/mpm/editorial/triplex-original/triplex-original-univers-01-triplex-original-univers-01-source.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "triplex-original-02",
      "order": 2,
      "eyebrow": "Au plus près",
      "title": "Matières fortes",
      "body": "Carbone, acier et précision.",
      "alt": "Triplex Original — matières fortes, photographie éditoriale.",
      "layout": "split-left",
      "animation": "reveal-mask",
      "src": "/media/mpm/editorial/triplex-original/triplex-original-univers-02-triplex-original-univers-02-macro.webp",
      "avif": "/media/mpm/editorial/triplex-original/triplex-original-univers-02-triplex-original-univers-02-macro.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "triplex-original-03",
      "order": 3,
      "eyebrow": "En mouvement",
      "title": "Tension maîtrisée",
      "body": "L’énergie prend une forme nette.",
      "alt": "Triplex Original — tension maîtrisée, photographie éditoriale.",
      "layout": "full-bleed",
      "animation": "reveal-mask",
      "src": "/media/mpm/editorial/triplex-original/triplex-original-univers-03-triplex-original-univers-03-splash.webp",
      "avif": "/media/mpm/editorial/triplex-original/triplex-original-univers-03-triplex-original-univers-03-splash.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "triplex-original-04",
      "order": 4,
      "eyebrow": "À plusieurs",
      "title": "Concentration",
      "body": "Créer longtemps, avancer ensemble.",
      "alt": "Triplex Original — concentration, photographie éditoriale.",
      "layout": "split-left",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/triplex-original/triplex-original-univers-04-triplex-original-univers-04-lifestyle-v02.webp",
      "avif": "/media/mpm/editorial/triplex-original/triplex-original-univers-04-triplex-original-univers-04-lifestyle-v02.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "triplex-original-05",
      "order": 5,
      "eyebrow": "Signature",
      "title": "Dans le mouvement",
      "body": "Chaque effort construit le suivant.",
      "alt": "Triplex Original — dans le mouvement, photographie éditoriale.",
      "layout": "split-right",
      "animation": "parallax-soft",
      "src": "/media/mpm/editorial/triplex-original/triplex-original-univers-05-triplex-original-univers-05-still-life.webp",
      "avif": "/media/mpm/editorial/triplex-original/triplex-original-univers-05-triplex-original-univers-05-still-life.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "triplex-original-06",
      "order": 6,
      "eyebrow": "Le geste",
      "title": "Tracer sa voie",
      "body": "La détermination éclaire la nuit.",
      "alt": "Triplex Original — tracer sa voie, photographie éditoriale.",
      "layout": "split-left",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/triplex-original/triplex-original-univers-06-triplex-original-univers-06-provenance.webp",
      "avif": "/media/mpm/editorial/triplex-original/triplex-original-univers-06-triplex-original-univers-06-provenance.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "triplex-original-07",
      "order": 7,
      "eyebrow": "La pause",
      "title": "Fraîcheur nette",
      "body": "Des bulles, du froid, aucun détour.",
      "alt": "Triplex Original — fraîcheur nette, photographie éditoriale.",
      "layout": "split-right",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/triplex-original/triplex-original-univers-07-triplex-original-univers-07-serve.webp",
      "avif": "/media/mpm/editorial/triplex-original/triplex-original-univers-07-triplex-original-univers-07-serve.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "triplex-original-08",
      "order": 8,
      "eyebrow": "L’élan",
      "title": "Même rythme",
      "body": "La force du collectif en mouvement.",
      "alt": "Triplex Original — même rythme, photographie éditoriale.",
      "layout": "split-left",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/triplex-original/triplex-original-univers-08-triplex-original-univers-08-culture.webp",
      "avif": "/media/mpm/editorial/triplex-original/triplex-original-univers-08-triplex-original-univers-08-culture.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "triplex-original-09",
      "order": 9,
      "eyebrow": "Sensation",
      "title": "Au plus près",
      "body": "Condensation, acier, éclat rouge.",
      "alt": "Triplex Original — au plus près, photographie éditoriale.",
      "layout": "split-right",
      "animation": "reveal-mask",
      "src": "/media/mpm/editorial/triplex-original/triplex-original-univers-09-triplex-original-univers-09-detail.webp",
      "avif": "/media/mpm/editorial/triplex-original/triplex-original-univers-09-triplex-original-univers-09-detail.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "triplex-original-10",
      "order": 10,
      "eyebrow": "Ensemble",
      "title": "Après l’effort",
      "body": "Le jour se lève sur ce qui avance.",
      "alt": "Triplex Original — après l’effort, photographie éditoriale.",
      "layout": "full-bleed",
      "animation": "parallax-soft",
      "src": "/media/mpm/editorial/triplex-original/triplex-original-univers-10-triplex-original-univers-10-finale.webp",
      "avif": "/media/mpm/editorial/triplex-original/triplex-original-univers-10-triplex-original-univers-10-finale.avif",
      "width": 1440,
      "height": 810
    }
  ],
  "tropicoul-ananas": [
    {
      "id": "tropicoul-ananas-01",
      "order": 1,
      "eyebrow": "Aux origines",
      "title": "Tout commence dans la matière",
      "body": "L’ananas affirme ses fibres, son éclat doré et sa fraîcheur dans un récit traversé de lumière. Cette première scène installe une identité vive, tropicale et lumineuse.",
      "alt": "Tropicoul Ananas — tout commence dans la matière, photographie éditoriale.",
      "layout": "full-bleed",
      "animation": "parallax-soft",
      "src": "/media/mpm/editorial/tropicoul-ananas/tropicoul-ananas-univers-01-tropicoul-ananas-univers-01-source.webp",
      "avif": "/media/mpm/editorial/tropicoul-ananas/tropicoul-ananas-univers-01-tropicoul-ananas-univers-01-source.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-ananas-02",
      "order": 2,
      "eyebrow": "Au plus près",
      "title": "La texture donne le ton",
      "body": "Au plus près, le ananas révèle ses reliefs et sa matière. Une image sensorielle, précise, sans artifice.",
      "alt": "Tropicoul Ananas — la texture donne le ton, photographie éditoriale.",
      "layout": "split-left",
      "animation": "reveal-mask",
      "src": "/media/mpm/editorial/tropicoul-ananas/tropicoul-ananas-univers-02-tropicoul-ananas-univers-02-macro.webp",
      "avif": "/media/mpm/editorial/tropicoul-ananas/tropicoul-ananas-univers-02-tropicoul-ananas-univers-02-macro.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-ananas-03",
      "order": 3,
      "eyebrow": "En mouvement",
      "title": "La fraîcheur prend vie",
      "body": "L’eau, la lumière et le ananas se rencontrent dans un mouvement vif qui traduit la sensation de fraîcheur.",
      "alt": "Tropicoul Ananas — la fraîcheur prend vie, photographie éditoriale.",
      "layout": "full-bleed",
      "animation": "reveal-mask",
      "src": "/media/mpm/editorial/tropicoul-ananas/tropicoul-ananas-univers-03-tropicoul-ananas-univers-03-splash.webp",
      "avif": "/media/mpm/editorial/tropicoul-ananas/tropicoul-ananas-univers-03-tropicoul-ananas-univers-03-splash.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-ananas-04",
      "order": 4,
      "eyebrow": "À plusieurs",
      "title": "Un moment qui rassemble",
      "body": "Une pause spontanée, un décor vivant, des échanges vrais : la saveur accompagne le moment sans le voler.",
      "alt": "Tropicoul Ananas — un moment qui rassemble, photographie éditoriale.",
      "layout": "split-left",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/tropicoul-ananas/tropicoul-ananas-univers-04-tropicoul-ananas-univers-04-lifestyle.webp",
      "avif": "/media/mpm/editorial/tropicoul-ananas/tropicoul-ananas-univers-04-tropicoul-ananas-univers-04-lifestyle.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-ananas-05",
      "order": 5,
      "eyebrow": "Signature",
      "title": "Une palette reconnaissable",
      "body": "Couleurs, volumes et ombres composent une signature vive, tropicale et lumineuse. Chaque élément prolonge l’identité du produit.",
      "alt": "Tropicoul Ananas — une palette reconnaissable, photographie éditoriale.",
      "layout": "split-right",
      "animation": "parallax-soft",
      "src": "/media/mpm/editorial/tropicoul-ananas/tropicoul-ananas-univers-05-tropicoul-ananas-univers-05-still-life.webp",
      "avif": "/media/mpm/editorial/tropicoul-ananas/tropicoul-ananas-univers-05-tropicoul-ananas-univers-05-still-life.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-ananas-06",
      "order": 6,
      "eyebrow": "Le geste",
      "title": "Choisir, préparer, transmettre",
      "body": "Du choix du ananas au geste de préparation, cette image replace la matière et le savoir-faire au cœur du récit.",
      "alt": "Tropicoul Ananas — choisir, préparer, transmettre, photographie éditoriale.",
      "layout": "split-left",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/tropicoul-ananas/tropicoul-ananas-univers-06-tropicoul-ananas-univers-06-provenance.webp",
      "avif": "/media/mpm/editorial/tropicoul-ananas/tropicoul-ananas-univers-06-tropicoul-ananas-univers-06-provenance.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-ananas-07",
      "order": 7,
      "eyebrow": "La pause",
      "title": "Fraîcheur en lumière",
      "body": "Servie fraîche, la boisson devient une respiration : condensation, lumière et simplicité installent l’envie.",
      "alt": "Tropicoul Ananas — fraîcheur en lumière, photographie éditoriale.",
      "layout": "split-right",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/tropicoul-ananas/tropicoul-ananas-univers-07-tropicoul-ananas-univers-07-serve.webp",
      "avif": "/media/mpm/editorial/tropicoul-ananas/tropicoul-ananas-univers-07-tropicoul-ananas-univers-07-serve.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-ananas-08",
      "order": 8,
      "eyebrow": "L’élan",
      "title": "Vivre le moment pleinement",
      "body": "Création, sport ou musique : le produit rejoint les instants où l’on avance, où l’on se retrouve, où l’on partage.",
      "alt": "Tropicoul Ananas — vivre le moment pleinement, photographie éditoriale.",
      "layout": "split-left",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/tropicoul-ananas/tropicoul-ananas-univers-08-tropicoul-ananas-univers-08-culture.webp",
      "avif": "/media/mpm/editorial/tropicoul-ananas/tropicoul-ananas-univers-08-tropicoul-ananas-univers-08-culture.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-ananas-09",
      "order": 9,
      "eyebrow": "Sensation",
      "title": "Bulles, matière et lumière",
      "body": "Bulles, gouttes et transparences offrent un dernier regard sur la sensation, plus proche et presque abstrait.",
      "alt": "Tropicoul Ananas — bulles, matière et lumière, photographie éditoriale.",
      "layout": "split-right",
      "animation": "reveal-mask",
      "src": "/media/mpm/editorial/tropicoul-ananas/tropicoul-ananas-univers-09-tropicoul-ananas-univers-09-detail.webp",
      "avif": "/media/mpm/editorial/tropicoul-ananas/tropicoul-ananas-univers-09-tropicoul-ananas-univers-09-detail.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-ananas-10",
      "order": 10,
      "eyebrow": "Ensemble",
      "title": "Le goût du partage",
      "body": "La narration s’achève autour d’un moment collectif. La saveur devient un souvenir que l’on partage.",
      "alt": "Tropicoul Ananas — le goût du partage, photographie éditoriale.",
      "layout": "full-bleed",
      "animation": "parallax-soft",
      "src": "/media/mpm/editorial/tropicoul-ananas/tropicoul-ananas-univers-10-tropicoul-ananas-univers-10-finale.webp",
      "avif": "/media/mpm/editorial/tropicoul-ananas/tropicoul-ananas-univers-10-tropicoul-ananas-univers-10-finale.avif",
      "width": 1440,
      "height": 810
    }
  ],
  "tropicoul-cocktail": [
    {
      "id": "tropicoul-cocktail-01",
      "order": 1,
      "eyebrow": "Aux origines",
      "title": "Tout commence dans la matière",
      "body": "Un assemblage fruité se dessine par la lumière, les reflets et le mouvement, sans figer la recette dans un seul fruit. Cette première scène installe une identité colorée, libre et expressive.",
      "alt": "Tropicoul Cocktail — tout commence dans la matière, photographie éditoriale.",
      "layout": "full-bleed",
      "animation": "parallax-soft",
      "src": "/media/mpm/editorial/tropicoul-cocktail/tropicoul-cocktail-univers-01-tropicoul-cocktail-univers-01-source.webp",
      "avif": "/media/mpm/editorial/tropicoul-cocktail/tropicoul-cocktail-univers-01-tropicoul-cocktail-univers-01-source.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-cocktail-02",
      "order": 2,
      "eyebrow": "Au plus près",
      "title": "La texture donne le ton",
      "body": "Au plus près, le assemblage fruité révèle ses reliefs et sa matière. Une image sensorielle, précise, sans artifice.",
      "alt": "Tropicoul Cocktail — la texture donne le ton, photographie éditoriale.",
      "layout": "split-left",
      "animation": "reveal-mask",
      "src": "/media/mpm/editorial/tropicoul-cocktail/tropicoul-cocktail-univers-02-tropicoul-cocktail-univers-02-macro.webp",
      "avif": "/media/mpm/editorial/tropicoul-cocktail/tropicoul-cocktail-univers-02-tropicoul-cocktail-univers-02-macro.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-cocktail-03",
      "order": 3,
      "eyebrow": "En mouvement",
      "title": "La fraîcheur prend vie",
      "body": "L’eau, la lumière et le assemblage fruité se rencontrent dans un mouvement vif qui traduit la sensation de fraîcheur.",
      "alt": "Tropicoul Cocktail — la fraîcheur prend vie, photographie éditoriale.",
      "layout": "full-bleed",
      "animation": "reveal-mask",
      "src": "/media/mpm/editorial/tropicoul-cocktail/tropicoul-cocktail-univers-03-tropicoul-cocktail-univers-03-splash.webp",
      "avif": "/media/mpm/editorial/tropicoul-cocktail/tropicoul-cocktail-univers-03-tropicoul-cocktail-univers-03-splash.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-cocktail-04",
      "order": 4,
      "eyebrow": "À plusieurs",
      "title": "Un moment qui rassemble",
      "body": "Une pause spontanée, un décor vivant, des échanges vrais : la saveur accompagne le moment sans le voler.",
      "alt": "Tropicoul Cocktail — un moment qui rassemble, photographie éditoriale.",
      "layout": "split-left",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/tropicoul-cocktail/tropicoul-cocktail-univers-04-tropicoul-cocktail-univers-04-lifestyle.webp",
      "avif": "/media/mpm/editorial/tropicoul-cocktail/tropicoul-cocktail-univers-04-tropicoul-cocktail-univers-04-lifestyle.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-cocktail-05",
      "order": 5,
      "eyebrow": "Signature",
      "title": "Une palette reconnaissable",
      "body": "Couleurs, volumes et ombres composent une signature colorée, libre et expressive. Chaque élément prolonge l’identité du produit.",
      "alt": "Tropicoul Cocktail — une palette reconnaissable, photographie éditoriale.",
      "layout": "split-right",
      "animation": "parallax-soft",
      "src": "/media/mpm/editorial/tropicoul-cocktail/tropicoul-cocktail-univers-05-tropicoul-cocktail-univers-05-still-life.webp",
      "avif": "/media/mpm/editorial/tropicoul-cocktail/tropicoul-cocktail-univers-05-tropicoul-cocktail-univers-05-still-life.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-cocktail-06",
      "order": 6,
      "eyebrow": "Le geste",
      "title": "Choisir, préparer, transmettre",
      "body": "Du choix du assemblage fruité au geste de préparation, cette image replace la matière et le savoir-faire au cœur du récit.",
      "alt": "Tropicoul Cocktail — choisir, préparer, transmettre, photographie éditoriale.",
      "layout": "split-left",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/tropicoul-cocktail/tropicoul-cocktail-univers-06-tropicoul-cocktail-univers-06-provenance.webp",
      "avif": "/media/mpm/editorial/tropicoul-cocktail/tropicoul-cocktail-univers-06-tropicoul-cocktail-univers-06-provenance.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-cocktail-07",
      "order": 7,
      "eyebrow": "La pause",
      "title": "Fraîcheur en lumière",
      "body": "Servie fraîche, la boisson devient une respiration : condensation, lumière et simplicité installent l’envie.",
      "alt": "Tropicoul Cocktail — fraîcheur en lumière, photographie éditoriale.",
      "layout": "split-right",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/tropicoul-cocktail/tropicoul-cocktail-univers-07-tropicoul-cocktail-univers-07-serve.webp",
      "avif": "/media/mpm/editorial/tropicoul-cocktail/tropicoul-cocktail-univers-07-tropicoul-cocktail-univers-07-serve.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-cocktail-08",
      "order": 8,
      "eyebrow": "L’élan",
      "title": "Vivre le moment pleinement",
      "body": "Création, sport ou musique : le produit rejoint les instants où l’on avance, où l’on se retrouve, où l’on partage.",
      "alt": "Tropicoul Cocktail — vivre le moment pleinement, photographie éditoriale.",
      "layout": "split-left",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/tropicoul-cocktail/tropicoul-cocktail-univers-08-tropicoul-cocktail-univers-08-culture.webp",
      "avif": "/media/mpm/editorial/tropicoul-cocktail/tropicoul-cocktail-univers-08-tropicoul-cocktail-univers-08-culture.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-cocktail-09",
      "order": 9,
      "eyebrow": "Sensation",
      "title": "Bulles, matière et lumière",
      "body": "Bulles, gouttes et transparences offrent un dernier regard sur la sensation, plus proche et presque abstrait.",
      "alt": "Tropicoul Cocktail — bulles, matière et lumière, photographie éditoriale.",
      "layout": "split-right",
      "animation": "reveal-mask",
      "src": "/media/mpm/editorial/tropicoul-cocktail/tropicoul-cocktail-univers-09-tropicoul-cocktail-univers-09-detail.webp",
      "avif": "/media/mpm/editorial/tropicoul-cocktail/tropicoul-cocktail-univers-09-tropicoul-cocktail-univers-09-detail.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-cocktail-10",
      "order": 10,
      "eyebrow": "Ensemble",
      "title": "Le goût du partage",
      "body": "La narration s’achève autour d’un moment collectif. La saveur devient un souvenir que l’on partage.",
      "alt": "Tropicoul Cocktail — le goût du partage, photographie éditoriale.",
      "layout": "full-bleed",
      "animation": "parallax-soft",
      "src": "/media/mpm/editorial/tropicoul-cocktail/tropicoul-cocktail-univers-10-tropicoul-cocktail-univers-10-finale.webp",
      "avif": "/media/mpm/editorial/tropicoul-cocktail/tropicoul-cocktail-univers-10-tropicoul-cocktail-univers-10-finale.avif",
      "width": 1440,
      "height": 810
    }
  ],
  "tropicoul-goyave": [
    {
      "id": "tropicoul-goyave-01",
      "order": 1,
      "eyebrow": "Aux origines",
      "title": "Tout commence dans la matière",
      "body": "La goyave associe chair rose, graines délicates et feuillage profond dans une fraîcheur tout en nuances. Cette première scène installe une identité douce, botanique et contemporaine.",
      "alt": "Tropicoul Goyave — tout commence dans la matière, photographie éditoriale.",
      "layout": "full-bleed",
      "animation": "parallax-soft",
      "src": "/media/mpm/editorial/tropicoul-goyave/tropicoul-goyave-univers-01-tropicoul-goyave-univers-01-source.webp",
      "avif": "/media/mpm/editorial/tropicoul-goyave/tropicoul-goyave-univers-01-tropicoul-goyave-univers-01-source.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-goyave-02",
      "order": 2,
      "eyebrow": "Au plus près",
      "title": "La texture donne le ton",
      "body": "Au plus près, le goyave révèle ses reliefs et sa matière. Une image sensorielle, précise, sans artifice.",
      "alt": "Tropicoul Goyave — la texture donne le ton, photographie éditoriale.",
      "layout": "split-left",
      "animation": "reveal-mask",
      "src": "/media/mpm/editorial/tropicoul-goyave/tropicoul-goyave-univers-02-tropicoul-goyave-univers-02-macro.webp",
      "avif": "/media/mpm/editorial/tropicoul-goyave/tropicoul-goyave-univers-02-tropicoul-goyave-univers-02-macro.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-goyave-03",
      "order": 3,
      "eyebrow": "En mouvement",
      "title": "La fraîcheur prend vie",
      "body": "L’eau, la lumière et le goyave se rencontrent dans un mouvement vif qui traduit la sensation de fraîcheur.",
      "alt": "Tropicoul Goyave — la fraîcheur prend vie, photographie éditoriale.",
      "layout": "full-bleed",
      "animation": "reveal-mask",
      "src": "/media/mpm/editorial/tropicoul-goyave/tropicoul-goyave-univers-03-tropicoul-goyave-univers-03-splash.webp",
      "avif": "/media/mpm/editorial/tropicoul-goyave/tropicoul-goyave-univers-03-tropicoul-goyave-univers-03-splash.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-goyave-04",
      "order": 4,
      "eyebrow": "À plusieurs",
      "title": "Un moment qui rassemble",
      "body": "Une pause spontanée, un décor vivant, des échanges vrais : la saveur accompagne le moment sans le voler.",
      "alt": "Tropicoul Goyave — un moment qui rassemble, photographie éditoriale.",
      "layout": "split-left",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/tropicoul-goyave/tropicoul-goyave-univers-04-tropicoul-goyave-univers-04-lifestyle.webp",
      "avif": "/media/mpm/editorial/tropicoul-goyave/tropicoul-goyave-univers-04-tropicoul-goyave-univers-04-lifestyle.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-goyave-05",
      "order": 5,
      "eyebrow": "Signature",
      "title": "Une palette reconnaissable",
      "body": "Couleurs, volumes et ombres composent une signature douce, botanique et contemporaine. Chaque élément prolonge l’identité du produit.",
      "alt": "Tropicoul Goyave — une palette reconnaissable, photographie éditoriale.",
      "layout": "split-right",
      "animation": "parallax-soft",
      "src": "/media/mpm/editorial/tropicoul-goyave/tropicoul-goyave-univers-05-tropicoul-goyave-univers-05-still-life.webp",
      "avif": "/media/mpm/editorial/tropicoul-goyave/tropicoul-goyave-univers-05-tropicoul-goyave-univers-05-still-life.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-goyave-06",
      "order": 6,
      "eyebrow": "Le geste",
      "title": "Choisir, préparer, transmettre",
      "body": "Du choix du goyave au geste de préparation, cette image replace la matière et le savoir-faire au cœur du récit.",
      "alt": "Tropicoul Goyave — choisir, préparer, transmettre, photographie éditoriale.",
      "layout": "split-left",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/tropicoul-goyave/tropicoul-goyave-univers-06-tropicoul-goyave-univers-06-provenance.webp",
      "avif": "/media/mpm/editorial/tropicoul-goyave/tropicoul-goyave-univers-06-tropicoul-goyave-univers-06-provenance.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-goyave-07",
      "order": 7,
      "eyebrow": "La pause",
      "title": "Fraîcheur en lumière",
      "body": "Servie fraîche, la boisson devient une respiration : condensation, lumière et simplicité installent l’envie.",
      "alt": "Tropicoul Goyave — fraîcheur en lumière, photographie éditoriale.",
      "layout": "split-right",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/tropicoul-goyave/tropicoul-goyave-univers-07-tropicoul-goyave-univers-07-serve.webp",
      "avif": "/media/mpm/editorial/tropicoul-goyave/tropicoul-goyave-univers-07-tropicoul-goyave-univers-07-serve.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-goyave-08",
      "order": 8,
      "eyebrow": "L’élan",
      "title": "Vivre le moment pleinement",
      "body": "Création, sport ou musique : le produit rejoint les instants où l’on avance, où l’on se retrouve, où l’on partage.",
      "alt": "Tropicoul Goyave — vivre le moment pleinement, photographie éditoriale.",
      "layout": "split-left",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/tropicoul-goyave/tropicoul-goyave-univers-08-tropicoul-goyave-univers-08-culture.webp",
      "avif": "/media/mpm/editorial/tropicoul-goyave/tropicoul-goyave-univers-08-tropicoul-goyave-univers-08-culture.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-goyave-09",
      "order": 9,
      "eyebrow": "Sensation",
      "title": "Bulles, matière et lumière",
      "body": "Bulles, gouttes et transparences offrent un dernier regard sur la sensation, plus proche et presque abstrait.",
      "alt": "Tropicoul Goyave — bulles, matière et lumière, photographie éditoriale.",
      "layout": "split-right",
      "animation": "reveal-mask",
      "src": "/media/mpm/editorial/tropicoul-goyave/tropicoul-goyave-univers-09-tropicoul-goyave-univers-09-detail.webp",
      "avif": "/media/mpm/editorial/tropicoul-goyave/tropicoul-goyave-univers-09-tropicoul-goyave-univers-09-detail.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-goyave-10",
      "order": 10,
      "eyebrow": "Ensemble",
      "title": "Le goût du partage",
      "body": "La narration s’achève autour d’un moment collectif. La saveur devient un souvenir que l’on partage.",
      "alt": "Tropicoul Goyave — le goût du partage, photographie éditoriale.",
      "layout": "full-bleed",
      "animation": "parallax-soft",
      "src": "/media/mpm/editorial/tropicoul-goyave/tropicoul-goyave-univers-10-tropicoul-goyave-univers-10-finale.webp",
      "avif": "/media/mpm/editorial/tropicoul-goyave/tropicoul-goyave-univers-10-tropicoul-goyave-univers-10-finale.avif",
      "width": 1440,
      "height": 810
    }
  ],
  "tropicoul-mangue": [
    {
      "id": "tropicoul-mangue-01",
      "order": 1,
      "eyebrow": "Aux origines",
      "title": "Tout commence dans la matière",
      "body": "La mangue dévoile une chair lumineuse et une rondeur visuelle qui donne le ton à toute l’expérience. Cette première scène installe une identité dorée, généreuse et solaire.",
      "alt": "Tropicoul Mangue — tout commence dans la matière, photographie éditoriale.",
      "layout": "full-bleed",
      "animation": "parallax-soft",
      "src": "/media/mpm/editorial/tropicoul-mangue/tropicoul-mangue-univers-01-tropicoul-mangue-univers-01-source.webp",
      "avif": "/media/mpm/editorial/tropicoul-mangue/tropicoul-mangue-univers-01-tropicoul-mangue-univers-01-source.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-mangue-02",
      "order": 2,
      "eyebrow": "Au plus près",
      "title": "La texture donne le ton",
      "body": "Au plus près, le mangue révèle ses reliefs et sa matière. Une image sensorielle, précise, sans artifice.",
      "alt": "Tropicoul Mangue — la texture donne le ton, photographie éditoriale.",
      "layout": "split-left",
      "animation": "reveal-mask",
      "src": "/media/mpm/editorial/tropicoul-mangue/tropicoul-mangue-univers-02-tropicoul-mangue-univers-02-macro.webp",
      "avif": "/media/mpm/editorial/tropicoul-mangue/tropicoul-mangue-univers-02-tropicoul-mangue-univers-02-macro.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-mangue-03",
      "order": 3,
      "eyebrow": "En mouvement",
      "title": "La fraîcheur prend vie",
      "body": "L’eau, la lumière et le mangue se rencontrent dans un mouvement vif qui traduit la sensation de fraîcheur.",
      "alt": "Tropicoul Mangue — la fraîcheur prend vie, photographie éditoriale.",
      "layout": "full-bleed",
      "animation": "reveal-mask",
      "src": "/media/mpm/editorial/tropicoul-mangue/tropicoul-mangue-univers-03-tropicoul-mangue-univers-03-splash.webp",
      "avif": "/media/mpm/editorial/tropicoul-mangue/tropicoul-mangue-univers-03-tropicoul-mangue-univers-03-splash.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-mangue-04",
      "order": 4,
      "eyebrow": "À plusieurs",
      "title": "Un moment qui rassemble",
      "body": "Une pause spontanée, un décor vivant, des échanges vrais : la saveur accompagne le moment sans le voler.",
      "alt": "Tropicoul Mangue — un moment qui rassemble, photographie éditoriale.",
      "layout": "split-left",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/tropicoul-mangue/tropicoul-mangue-univers-04-tropicoul-mangue-univers-04-lifestyle.webp",
      "avif": "/media/mpm/editorial/tropicoul-mangue/tropicoul-mangue-univers-04-tropicoul-mangue-univers-04-lifestyle.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-mangue-05",
      "order": 5,
      "eyebrow": "Signature",
      "title": "Une palette reconnaissable",
      "body": "Couleurs, volumes et ombres composent une signature dorée, généreuse et solaire. Chaque élément prolonge l’identité du produit.",
      "alt": "Tropicoul Mangue — une palette reconnaissable, photographie éditoriale.",
      "layout": "split-right",
      "animation": "parallax-soft",
      "src": "/media/mpm/editorial/tropicoul-mangue/tropicoul-mangue-univers-05-tropicoul-mangue-univers-05-still-life.webp",
      "avif": "/media/mpm/editorial/tropicoul-mangue/tropicoul-mangue-univers-05-tropicoul-mangue-univers-05-still-life.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-mangue-06",
      "order": 6,
      "eyebrow": "Le geste",
      "title": "Choisir, préparer, transmettre",
      "body": "Du choix du mangue au geste de préparation, cette image replace la matière et le savoir-faire au cœur du récit.",
      "alt": "Tropicoul Mangue — choisir, préparer, transmettre, photographie éditoriale.",
      "layout": "split-left",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/tropicoul-mangue/tropicoul-mangue-univers-06-tropicoul-mangue-univers-06-provenance.webp",
      "avif": "/media/mpm/editorial/tropicoul-mangue/tropicoul-mangue-univers-06-tropicoul-mangue-univers-06-provenance.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-mangue-07",
      "order": 7,
      "eyebrow": "La pause",
      "title": "Fraîcheur en lumière",
      "body": "Servie fraîche, la boisson devient une respiration : condensation, lumière et simplicité installent l’envie.",
      "alt": "Tropicoul Mangue — fraîcheur en lumière, photographie éditoriale.",
      "layout": "split-right",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/tropicoul-mangue/tropicoul-mangue-univers-07-tropicoul-mangue-univers-07-serve.webp",
      "avif": "/media/mpm/editorial/tropicoul-mangue/tropicoul-mangue-univers-07-tropicoul-mangue-univers-07-serve.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-mangue-08",
      "order": 8,
      "eyebrow": "L’élan",
      "title": "Vivre le moment pleinement",
      "body": "Création, sport ou musique : le produit rejoint les instants où l’on avance, où l’on se retrouve, où l’on partage.",
      "alt": "Tropicoul Mangue — vivre le moment pleinement, photographie éditoriale.",
      "layout": "split-left",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/tropicoul-mangue/tropicoul-mangue-univers-08-tropicoul-mangue-univers-08-culture.webp",
      "avif": "/media/mpm/editorial/tropicoul-mangue/tropicoul-mangue-univers-08-tropicoul-mangue-univers-08-culture.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-mangue-09",
      "order": 9,
      "eyebrow": "Sensation",
      "title": "Bulles, matière et lumière",
      "body": "Bulles, gouttes et transparences offrent un dernier regard sur la sensation, plus proche et presque abstrait.",
      "alt": "Tropicoul Mangue — bulles, matière et lumière, photographie éditoriale.",
      "layout": "split-right",
      "animation": "reveal-mask",
      "src": "/media/mpm/editorial/tropicoul-mangue/tropicoul-mangue-univers-09-tropicoul-mangue-univers-09-detail.webp",
      "avif": "/media/mpm/editorial/tropicoul-mangue/tropicoul-mangue-univers-09-tropicoul-mangue-univers-09-detail.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-mangue-10",
      "order": 10,
      "eyebrow": "Ensemble",
      "title": "Le goût du partage",
      "body": "La narration s’achève autour d’un moment collectif. La saveur devient un souvenir que l’on partage.",
      "alt": "Tropicoul Mangue — le goût du partage, photographie éditoriale.",
      "layout": "full-bleed",
      "animation": "parallax-soft",
      "src": "/media/mpm/editorial/tropicoul-mangue/tropicoul-mangue-univers-10-tropicoul-mangue-univers-10-finale.webp",
      "avif": "/media/mpm/editorial/tropicoul-mangue/tropicoul-mangue-univers-10-tropicoul-mangue-univers-10-finale.avif",
      "width": 1440,
      "height": 810
    }
  ],
  "tropicoul-orange": [
    {
      "id": "tropicoul-orange-01",
      "order": 1,
      "eyebrow": "Aux origines",
      "title": "Tout commence dans la matière",
      "body": "L’orange révèle sa pulpe, ses huiles et son énergie dans un dialogue graphique avec le bleu cobalt. Cette première scène installe une identité franche, vive et rythmée.",
      "alt": "Tropicoul Orange — tout commence dans la matière, photographie éditoriale.",
      "layout": "full-bleed",
      "animation": "parallax-soft",
      "src": "/media/mpm/editorial/tropicoul-orange/tropicoul-orange-univers-01-tropicoul-orange-univers-01-source.webp",
      "avif": "/media/mpm/editorial/tropicoul-orange/tropicoul-orange-univers-01-tropicoul-orange-univers-01-source.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-orange-02",
      "order": 2,
      "eyebrow": "Au plus près",
      "title": "La texture donne le ton",
      "body": "Au plus près, le orange révèle ses reliefs et sa matière. Une image sensorielle, précise, sans artifice.",
      "alt": "Tropicoul Orange — la texture donne le ton, photographie éditoriale.",
      "layout": "split-left",
      "animation": "reveal-mask",
      "src": "/media/mpm/editorial/tropicoul-orange/tropicoul-orange-univers-02-tropicoul-orange-univers-02-macro.webp",
      "avif": "/media/mpm/editorial/tropicoul-orange/tropicoul-orange-univers-02-tropicoul-orange-univers-02-macro.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-orange-03",
      "order": 3,
      "eyebrow": "En mouvement",
      "title": "La fraîcheur prend vie",
      "body": "L’eau, la lumière et le orange se rencontrent dans un mouvement vif qui traduit la sensation de fraîcheur.",
      "alt": "Tropicoul Orange — la fraîcheur prend vie, photographie éditoriale.",
      "layout": "full-bleed",
      "animation": "reveal-mask",
      "src": "/media/mpm/editorial/tropicoul-orange/tropicoul-orange-univers-03-tropicoul-orange-univers-03-splash.webp",
      "avif": "/media/mpm/editorial/tropicoul-orange/tropicoul-orange-univers-03-tropicoul-orange-univers-03-splash.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-orange-04",
      "order": 4,
      "eyebrow": "À plusieurs",
      "title": "Un moment qui rassemble",
      "body": "Une pause spontanée, un décor vivant, des échanges vrais : la saveur accompagne le moment sans le voler.",
      "alt": "Tropicoul Orange — un moment qui rassemble, photographie éditoriale.",
      "layout": "split-left",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/tropicoul-orange/tropicoul-orange-univers-04-tropicoul-orange-univers-04-lifestyle.webp",
      "avif": "/media/mpm/editorial/tropicoul-orange/tropicoul-orange-univers-04-tropicoul-orange-univers-04-lifestyle.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-orange-05",
      "order": 5,
      "eyebrow": "Signature",
      "title": "Une palette reconnaissable",
      "body": "Couleurs, volumes et ombres composent une signature franche, vive et rythmée. Chaque élément prolonge l’identité du produit.",
      "alt": "Tropicoul Orange — une palette reconnaissable, photographie éditoriale.",
      "layout": "split-right",
      "animation": "parallax-soft",
      "src": "/media/mpm/editorial/tropicoul-orange/tropicoul-orange-univers-05-tropicoul-orange-univers-05-still-life.webp",
      "avif": "/media/mpm/editorial/tropicoul-orange/tropicoul-orange-univers-05-tropicoul-orange-univers-05-still-life.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-orange-06",
      "order": 6,
      "eyebrow": "Le geste",
      "title": "Choisir, préparer, transmettre",
      "body": "Du choix du orange au geste de préparation, cette image replace la matière et le savoir-faire au cœur du récit.",
      "alt": "Tropicoul Orange — choisir, préparer, transmettre, photographie éditoriale.",
      "layout": "split-left",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/tropicoul-orange/tropicoul-orange-univers-06-tropicoul-orange-univers-06-provenance.webp",
      "avif": "/media/mpm/editorial/tropicoul-orange/tropicoul-orange-univers-06-tropicoul-orange-univers-06-provenance.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-orange-07",
      "order": 7,
      "eyebrow": "La pause",
      "title": "Fraîcheur en lumière",
      "body": "Servie fraîche, la boisson devient une respiration : condensation, lumière et simplicité installent l’envie.",
      "alt": "Tropicoul Orange — fraîcheur en lumière, photographie éditoriale.",
      "layout": "split-right",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/tropicoul-orange/tropicoul-orange-univers-07-tropicoul-orange-univers-07-serve.webp",
      "avif": "/media/mpm/editorial/tropicoul-orange/tropicoul-orange-univers-07-tropicoul-orange-univers-07-serve.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-orange-08",
      "order": 8,
      "eyebrow": "L’élan",
      "title": "Vivre le moment pleinement",
      "body": "Création, sport ou musique : le produit rejoint les instants où l’on avance, où l’on se retrouve, où l’on partage.",
      "alt": "Tropicoul Orange — vivre le moment pleinement, photographie éditoriale.",
      "layout": "split-left",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/tropicoul-orange/tropicoul-orange-univers-08-tropicoul-orange-univers-08-culture.webp",
      "avif": "/media/mpm/editorial/tropicoul-orange/tropicoul-orange-univers-08-tropicoul-orange-univers-08-culture.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-orange-09",
      "order": 9,
      "eyebrow": "Sensation",
      "title": "Bulles, matière et lumière",
      "body": "Bulles, gouttes et transparences offrent un dernier regard sur la sensation, plus proche et presque abstrait.",
      "alt": "Tropicoul Orange — bulles, matière et lumière, photographie éditoriale.",
      "layout": "split-right",
      "animation": "reveal-mask",
      "src": "/media/mpm/editorial/tropicoul-orange/tropicoul-orange-univers-09-tropicoul-orange-univers-09-detail.webp",
      "avif": "/media/mpm/editorial/tropicoul-orange/tropicoul-orange-univers-09-tropicoul-orange-univers-09-detail.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-orange-10",
      "order": 10,
      "eyebrow": "Ensemble",
      "title": "Le goût du partage",
      "body": "La narration s’achève autour d’un moment collectif. La saveur devient un souvenir que l’on partage.",
      "alt": "Tropicoul Orange — le goût du partage, photographie éditoriale.",
      "layout": "full-bleed",
      "animation": "parallax-soft",
      "src": "/media/mpm/editorial/tropicoul-orange/tropicoul-orange-univers-10-tropicoul-orange-univers-10-finale-v03.webp",
      "avif": "/media/mpm/editorial/tropicoul-orange/tropicoul-orange-univers-10-tropicoul-orange-univers-10-finale-v03.avif",
      "width": 1440,
      "height": 810
    }
  ],
  "tropicoul-tamarin": [
    {
      "id": "tropicoul-tamarin-01",
      "order": 1,
      "eyebrow": "Aux origines",
      "title": "Tout commence dans la matière",
      "body": "Le tamarin raconte ses gousses, ses fibres et ses tonalités ambrées dans un univers calme et mature. Cette première scène installe une identité profonde, tactile et ambrée.",
      "alt": "Tropicoul Tamarin — tout commence dans la matière, photographie éditoriale.",
      "layout": "full-bleed",
      "animation": "parallax-soft",
      "src": "/media/mpm/editorial/tropicoul-tamarin/tropicoul-tamarin-univers-01-tropicoul-tamarin-univers-01-source.webp",
      "avif": "/media/mpm/editorial/tropicoul-tamarin/tropicoul-tamarin-univers-01-tropicoul-tamarin-univers-01-source.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-tamarin-02",
      "order": 2,
      "eyebrow": "Au plus près",
      "title": "La texture donne le ton",
      "body": "Au plus près, le tamarin révèle ses reliefs et sa matière. Une image sensorielle, précise, sans artifice.",
      "alt": "Tropicoul Tamarin — la texture donne le ton, photographie éditoriale.",
      "layout": "split-left",
      "animation": "reveal-mask",
      "src": "/media/mpm/editorial/tropicoul-tamarin/tropicoul-tamarin-univers-02-tropicoul-tamarin-univers-02-macro.webp",
      "avif": "/media/mpm/editorial/tropicoul-tamarin/tropicoul-tamarin-univers-02-tropicoul-tamarin-univers-02-macro.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-tamarin-03",
      "order": 3,
      "eyebrow": "En mouvement",
      "title": "La fraîcheur prend vie",
      "body": "L’eau, la lumière et le tamarin se rencontrent dans un mouvement vif qui traduit la sensation de fraîcheur.",
      "alt": "Tropicoul Tamarin — la fraîcheur prend vie, photographie éditoriale.",
      "layout": "full-bleed",
      "animation": "reveal-mask",
      "src": "/media/mpm/editorial/tropicoul-tamarin/tropicoul-tamarin-univers-03-tropicoul-tamarin-univers-03-splash.webp",
      "avif": "/media/mpm/editorial/tropicoul-tamarin/tropicoul-tamarin-univers-03-tropicoul-tamarin-univers-03-splash.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-tamarin-04",
      "order": 4,
      "eyebrow": "À plusieurs",
      "title": "Un moment qui rassemble",
      "body": "Une pause spontanée, un décor vivant, des échanges vrais : la saveur accompagne le moment sans le voler.",
      "alt": "Tropicoul Tamarin — un moment qui rassemble, photographie éditoriale.",
      "layout": "split-left",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/tropicoul-tamarin/tropicoul-tamarin-univers-04-tropicoul-tamarin-univers-04-lifestyle.webp",
      "avif": "/media/mpm/editorial/tropicoul-tamarin/tropicoul-tamarin-univers-04-tropicoul-tamarin-univers-04-lifestyle.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-tamarin-05",
      "order": 5,
      "eyebrow": "Signature",
      "title": "Une palette reconnaissable",
      "body": "Couleurs, volumes et ombres composent une signature profonde, tactile et ambrée. Chaque élément prolonge l’identité du produit.",
      "alt": "Tropicoul Tamarin — une palette reconnaissable, photographie éditoriale.",
      "layout": "split-right",
      "animation": "parallax-soft",
      "src": "/media/mpm/editorial/tropicoul-tamarin/tropicoul-tamarin-univers-05-tropicoul-tamarin-univers-05-still-life.webp",
      "avif": "/media/mpm/editorial/tropicoul-tamarin/tropicoul-tamarin-univers-05-tropicoul-tamarin-univers-05-still-life.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-tamarin-06",
      "order": 6,
      "eyebrow": "Le geste",
      "title": "Choisir, préparer, transmettre",
      "body": "Du choix du tamarin au geste de préparation, cette image replace la matière et le savoir-faire au cœur du récit.",
      "alt": "Tropicoul Tamarin — choisir, préparer, transmettre, photographie éditoriale.",
      "layout": "split-left",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/tropicoul-tamarin/tropicoul-tamarin-univers-06-tropicoul-tamarin-univers-06-provenance.webp",
      "avif": "/media/mpm/editorial/tropicoul-tamarin/tropicoul-tamarin-univers-06-tropicoul-tamarin-univers-06-provenance.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-tamarin-07",
      "order": 7,
      "eyebrow": "La pause",
      "title": "Fraîcheur en lumière",
      "body": "Servie fraîche, la boisson devient une respiration : condensation, lumière et simplicité installent l’envie.",
      "alt": "Tropicoul Tamarin — fraîcheur en lumière, photographie éditoriale.",
      "layout": "split-right",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/tropicoul-tamarin/tropicoul-tamarin-univers-07-tropicoul-tamarin-univers-07-serve.webp",
      "avif": "/media/mpm/editorial/tropicoul-tamarin/tropicoul-tamarin-univers-07-tropicoul-tamarin-univers-07-serve.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-tamarin-08",
      "order": 8,
      "eyebrow": "L’élan",
      "title": "Vivre le moment pleinement",
      "body": "Création, sport ou musique : le produit rejoint les instants où l’on avance, où l’on se retrouve, où l’on partage.",
      "alt": "Tropicoul Tamarin — vivre le moment pleinement, photographie éditoriale.",
      "layout": "split-left",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/tropicoul-tamarin/tropicoul-tamarin-univers-08-tropicoul-tamarin-univers-08-culture.webp",
      "avif": "/media/mpm/editorial/tropicoul-tamarin/tropicoul-tamarin-univers-08-tropicoul-tamarin-univers-08-culture.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-tamarin-09",
      "order": 9,
      "eyebrow": "Sensation",
      "title": "Bulles, matière et lumière",
      "body": "Bulles, gouttes et transparences offrent un dernier regard sur la sensation, plus proche et presque abstrait.",
      "alt": "Tropicoul Tamarin — bulles, matière et lumière, photographie éditoriale.",
      "layout": "split-right",
      "animation": "reveal-mask",
      "src": "/media/mpm/editorial/tropicoul-tamarin/tropicoul-tamarin-univers-09-tropicoul-tamarin-univers-09-detail.webp",
      "avif": "/media/mpm/editorial/tropicoul-tamarin/tropicoul-tamarin-univers-09-tropicoul-tamarin-univers-09-detail.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "tropicoul-tamarin-10",
      "order": 10,
      "eyebrow": "Ensemble",
      "title": "Le goût du partage",
      "body": "La narration s’achève autour d’un moment collectif. La saveur devient un souvenir que l’on partage.",
      "alt": "Tropicoul Tamarin — le goût du partage, photographie éditoriale.",
      "layout": "full-bleed",
      "animation": "parallax-soft",
      "src": "/media/mpm/editorial/tropicoul-tamarin/tropicoul-tamarin-univers-10-tropicoul-tamarin-univers-10-finale.webp",
      "avif": "/media/mpm/editorial/tropicoul-tamarin/tropicoul-tamarin-univers-10-tropicoul-tamarin-univers-10-finale.avif",
      "width": 1440,
      "height": 810
    }
  ],
  "vimto-sparkling": [
    {
      "id": "vimto-sparkling-01",
      "order": 1,
      "eyebrow": "Aux origines",
      "title": "Une gamme, plusieurs expressions",
      "body": "Vimto classique et Vimto Malt se rencontrent dans une famille de formats pensée pour différents moments.",
      "alt": "Univers Vimto — une gamme, plusieurs expressions, photographie éditoriale.",
      "layout": "full-bleed",
      "animation": "parallax-soft",
      "src": "/media/mpm/editorial/vimto-sparkling/vimto-sparkling-univers-01-vimto-sparkling-univers-01-source-v02.webp",
      "avif": "/media/mpm/editorial/vimto-sparkling/vimto-sparkling-univers-01-vimto-sparkling-univers-01-source-v02.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "vimto-sparkling-02",
      "order": 2,
      "eyebrow": "Au plus près",
      "title": "L’héritage en bouteille",
      "body": "Le verre, la couleur profonde et l’étiquette historique installent une présence reconnaissable au premier regard.",
      "alt": "Univers Vimto — l’héritage en bouteille, photographie éditoriale.",
      "layout": "split-left",
      "animation": "reveal-mask",
      "src": "/media/mpm/editorial/vimto-sparkling/vimto-sparkling-univers-02-vimto-sparkling-univers-02-macro.webp",
      "avif": "/media/mpm/editorial/vimto-sparkling/vimto-sparkling-univers-02-vimto-sparkling-univers-02-macro.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "vimto-sparkling-03",
      "order": 3,
      "eyebrow": "En mouvement",
      "title": "L’icône rouge",
      "body": "La canette Sparkling affirme un langage rouge, blanc et jaune, vif et immédiatement identifiable.",
      "alt": "Univers Vimto — l’icône rouge, photographie éditoriale.",
      "layout": "full-bleed",
      "animation": "reveal-mask",
      "src": "/media/mpm/editorial/vimto-sparkling/vimto-sparkling-univers-03-vimto-sparkling-univers-03-splash.webp",
      "avif": "/media/mpm/editorial/vimto-sparkling/vimto-sparkling-univers-03-vimto-sparkling-univers-03-splash.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "vimto-sparkling-04",
      "order": 4,
      "eyebrow": "À plusieurs",
      "title": "Le territoire Malt",
      "body": "Une identité plus sombre, des accents rouges et jaunes, et une présence qui se distingue sans quitter la famille Vimto.",
      "alt": "Univers Vimto — le territoire malt, photographie éditoriale.",
      "layout": "split-left",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/vimto-sparkling/vimto-sparkling-univers-04-vimto-sparkling-univers-04-lifestyle-v03.webp",
      "avif": "/media/mpm/editorial/vimto-sparkling/vimto-sparkling-univers-04-vimto-sparkling-univers-04-lifestyle-v03.avif",
      "width": 1672,
      "height": 941
    },
    {
      "id": "vimto-sparkling-05",
      "order": 5,
      "eyebrow": "Signature",
      "title": "Une signature fruitée",
      "body": "Fruits noirs, fraîcheur et mouvement composent le cœur sensoriel de l’univers classique.",
      "alt": "Univers Vimto — une signature fruitée, photographie éditoriale.",
      "layout": "split-right",
      "animation": "parallax-soft",
      "src": "/media/mpm/editorial/vimto-sparkling/vimto-sparkling-univers-05-vimto-sparkling-univers-05-still-life.webp",
      "avif": "/media/mpm/editorial/vimto-sparkling/vimto-sparkling-univers-05-vimto-sparkling-univers-05-still-life.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "vimto-sparkling-06",
      "order": 6,
      "eyebrow": "Le geste",
      "title": "Les moments qui rassemblent",
      "body": "À l’occasion de Tabaski comme au quotidien, les formats trouvent naturellement leur place sur une table partagée.",
      "alt": "Univers Vimto — les moments qui rassemblent, photographie éditoriale.",
      "layout": "split-left",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/vimto-sparkling/vimto-sparkling-univers-06-vimto-sparkling-univers-06-provenance-v04.webp",
      "avif": "/media/mpm/editorial/vimto-sparkling/vimto-sparkling-univers-06-vimto-sparkling-univers-06-provenance-v04.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "vimto-sparkling-07",
      "order": 7,
      "eyebrow": "La pause",
      "title": "Le geste du service",
      "body": "La bouteille verre prolonge le rituel : verser, faire pétiller, servir très frais.",
      "alt": "Univers Vimto — le geste du service, photographie éditoriale.",
      "layout": "split-right",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/vimto-sparkling/vimto-sparkling-univers-07-vimto-sparkling-univers-07-serve-v02.webp",
      "avif": "/media/mpm/editorial/vimto-sparkling/vimto-sparkling-univers-07-vimto-sparkling-univers-07-serve-v02.avif",
      "width": 1672,
      "height": 941
    },
    {
      "id": "vimto-sparkling-08",
      "order": 8,
      "eyebrow": "L’élan",
      "title": "À chacun son format",
      "body": "Bouteille ou canette, classique ou Malt : la gamme conserve des identités claires et complémentaires.",
      "alt": "Univers Vimto — à chacun son format, photographie éditoriale.",
      "layout": "split-left",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/vimto-sparkling/vimto-sparkling-univers-08-vimto-sparkling-univers-08-culture-v03.webp",
      "avif": "/media/mpm/editorial/vimto-sparkling/vimto-sparkling-univers-08-vimto-sparkling-univers-08-culture-v03.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "vimto-sparkling-09",
      "order": 9,
      "eyebrow": "Sensation",
      "title": "Au plus près",
      "body": "Verre, aluminium, condensation, fruits et céréales révèlent la diversité des matières de la gamme.",
      "alt": "Univers Vimto — au plus près, photographie éditoriale.",
      "layout": "split-right",
      "animation": "reveal-mask",
      "src": "/media/mpm/editorial/vimto-sparkling/vimto-sparkling-univers-09-vimto-sparkling-univers-09-detail-v02.webp",
      "avif": "/media/mpm/editorial/vimto-sparkling/vimto-sparkling-univers-09-vimto-sparkling-univers-09-detail-v02.avif",
      "width": 1440,
      "height": 810
    },
    {
      "id": "vimto-sparkling-10",
      "order": 10,
      "eyebrow": "Ensemble",
      "title": "Un même esprit de partage",
      "body": "Plusieurs expressions, une même table : l’univers Vimto s’achève sur un moment collectif et vivant.",
      "alt": "Univers Vimto — un même esprit de partage, photographie éditoriale.",
      "layout": "full-bleed",
      "animation": "parallax-soft",
      "src": "/media/mpm/editorial/vimto-sparkling/vimto-sparkling-univers-10-vimto-sparkling-univers-10-finale-v02.webp",
      "avif": "/media/mpm/editorial/vimto-sparkling/vimto-sparkling-univers-10-vimto-sparkling-univers-10-finale-v02.avif",
      "width": 1440,
      "height": 810
    }
  ],
  "vimto-sirop": [
    {
      "id": "vimto-sirop-01",
      "order": 1,
      "eyebrow": "La signature",
      "title": "Le rituel commence ici",
      "body": "Une bouteille, un verre servi très frais et la profondeur fruitée de Vimto.",
      "alt": "Bouteille de sirop Vimto et verre de boisson rouge avec glaçons sur une table en bois.",
      "layout": "full-bleed",
      "animation": "parallax-soft",
      "src": "/media/mpm/editorial/vimto-sirop/vimto-sirop-univers-01-signature-v01.webp",
      "avif": "/media/mpm/editorial/vimto-sirop/vimto-sirop-univers-01-signature-v01.avif",
      "width": 1680,
      "height": 945
    },
    {
      "id": "vimto-sirop-02",
      "order": 2,
      "eyebrow": "Le geste",
      "title": "Verser, puis partager",
      "body": "Le sirop Vimto se révèle dans un verre plein de glaçons, au moment précis du service.",
      "alt": "Bouteille de sirop Vimto versant une boisson rouge dans un grand verre rempli de glaçons.",
      "layout": "split-left",
      "animation": "reveal-mask",
      "src": "/media/mpm/editorial/vimto-sirop/vimto-sirop-univers-02-verse-v01.webp",
      "avif": "/media/mpm/editorial/vimto-sirop/vimto-sirop-univers-02-verse-v01.avif",
      "width": 1680,
      "height": 945
    },
    {
      "id": "vimto-sirop-03",
      "order": 3,
      "eyebrow": "À table",
      "title": "Le plaisir du service",
      "body": "Pichet, verres et fruits composent une table prête pour les moments partagés.",
      "alt": "Bouteille de sirop Vimto, pichet et verres servis sur une table de repas en extérieur.",
      "layout": "split-right",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/vimto-sirop/vimto-sirop-univers-03-table-v01.webp",
      "avif": "/media/mpm/editorial/vimto-sirop/vimto-sirop-univers-03-table-v01.avif",
      "width": 1680,
      "height": 945
    },
    {
      "id": "vimto-sirop-04",
      "order": 4,
      "eyebrow": "Très frais",
      "title": "La fraîcheur en réserve",
      "body": "La bouteille se garde au frais, entourée de glace et de fruits de la signature Vimto.",
      "alt": "Bouteille de sirop Vimto dans un seau rempli de glace, avec des fruits rouges.",
      "layout": "split-left",
      "animation": "parallax-soft",
      "src": "/media/mpm/editorial/vimto-sirop/vimto-sirop-univers-04-fraicheur-v01.webp",
      "avif": "/media/mpm/editorial/vimto-sirop/vimto-sirop-univers-04-fraicheur-v01.avif",
      "width": 1680,
      "height": 945
    },
    {
      "id": "vimto-sirop-05",
      "order": 5,
      "eyebrow": "Le détail",
      "title": "Une palette à composer",
      "body": "Fruits, agrumes et service frais : chaque plateau donne son rythme au sirop Vimto.",
      "alt": "Vue de dessus d'une bouteille de sirop Vimto, d'un verre servi et de fruits sur un plateau.",
      "layout": "split-right",
      "animation": "reveal-mask",
      "src": "/media/mpm/editorial/vimto-sirop/vimto-sirop-univers-05-plateau-v01.webp",
      "avif": "/media/mpm/editorial/vimto-sirop/vimto-sirop-univers-05-plateau-v01.avif",
      "width": 1680,
      "height": 945
    },
    {
      "id": "vimto-sirop-06",
      "order": 6,
      "eyebrow": "Le soir",
      "title": "Prendre le temps",
      "body": "Un verre lumineux et la bouteille Vimto installent un moment calme, à savourer sans se presser.",
      "alt": "Bouteille de sirop Vimto et grand verre rouge sur un rebord de fenêtre le soir.",
      "layout": "full-bleed",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/vimto-sirop/vimto-sirop-univers-06-nuit-v01.webp",
      "avif": "/media/mpm/editorial/vimto-sirop/vimto-sirop-univers-06-nuit-v01.avif",
      "width": 1680,
      "height": 945
    }
  ],
  "vimto-malt": [
    {
      "id": "vimto-malt-01",
      "order": 1,
      "eyebrow": "La signature",
      "title": "Une profondeur maltée",
      "body": "La fraîcheur de Vimto rencontre une note maltée, révélée dans un verre généreux.",
      "alt": "Canette Vimto Malt, verre de boisson ambrée, épis de blé et fruits rouges sur une table sombre.",
      "layout": "full-bleed",
      "animation": "parallax-soft",
      "src": "/media/mpm/editorial/vimto-malt/vimto-malt-univers-01-signature-v01.webp",
      "avif": "/media/mpm/editorial/vimto-malt/vimto-malt-univers-01-signature-v01.avif",
      "width": 1680,
      "height": 945
    },
    {
      "id": "vimto-malt-02",
      "order": 2,
      "eyebrow": "Le geste",
      "title": "Servir très frais",
      "body": "Versé sur glace, Vimto Malt dévoile une expression ample et intense.",
      "alt": "Canette Vimto Malt versant une boisson ambrée dans un grand verre avec glaçons.",
      "layout": "split-left",
      "animation": "reveal-mask",
      "src": "/media/mpm/editorial/vimto-malt/vimto-malt-univers-02-verse-v01.webp",
      "avif": "/media/mpm/editorial/vimto-malt/vimto-malt-univers-02-verse-v01.avif",
      "width": 1680,
      "height": 945
    },
    {
      "id": "vimto-malt-03",
      "order": 3,
      "eyebrow": "À table",
      "title": "Le goût du partage",
      "body": "Sur un plateau servi, le malt accompagne les échanges avec une présence chaleureuse.",
      "alt": "Canette Vimto Malt, verres et fruits rouges sur un plateau dans une cour ensoleillée.",
      "layout": "split-right",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/vimto-malt/vimto-malt-univers-03-table-v01.webp",
      "avif": "/media/mpm/editorial/vimto-malt/vimto-malt-univers-03-table-v01.avif",
      "width": 1680,
      "height": 945
    },
    {
      "id": "vimto-malt-04",
      "order": 4,
      "eyebrow": "Très frais",
      "title": "La fraîcheur en réserve",
      "body": "Glace, condensation et grains de malt : la canette se prépare pour le moment de service.",
      "alt": "Canette Vimto Malt dans un seau à glace avec des baies rouges et des épis de blé.",
      "layout": "split-left",
      "animation": "parallax-soft",
      "src": "/media/mpm/editorial/vimto-malt/vimto-malt-univers-04-fraicheur-v01.webp",
      "avif": "/media/mpm/editorial/vimto-malt/vimto-malt-univers-04-fraicheur-v01.avif",
      "width": 1680,
      "height": 945
    },
    {
      "id": "vimto-malt-05",
      "order": 5,
      "eyebrow": "Le détail",
      "title": "La matière en partage",
      "body": "Un plateau, des fruits et des céréales pour faire dialoguer les nuances de Vimto Malt.",
      "alt": "Vue de dessus d'une canette Vimto Malt, d'un verre et d'épis de blé sur un plateau doré.",
      "layout": "split-right",
      "animation": "reveal-mask",
      "src": "/media/mpm/editorial/vimto-malt/vimto-malt-univers-05-plateau-v01.webp",
      "avif": "/media/mpm/editorial/vimto-malt/vimto-malt-univers-05-plateau-v01.avif",
      "width": 1680,
      "height": 945
    },
    {
      "id": "vimto-malt-06",
      "order": 6,
      "eyebrow": "L’équilibre",
      "title": "Fruit et malt, réunis",
      "body": "Les baies, les grains et la boisson ambrée traduisent les deux facettes de Vimto Malt.",
      "alt": "Canette Vimto Malt, verre ambré, baies rouges et céréales sur une table en bois sombre.",
      "layout": "full-bleed",
      "animation": "fade-rise",
      "src": "/media/mpm/editorial/vimto-malt/vimto-malt-univers-06-grains-v01.webp",
      "avif": "/media/mpm/editorial/vimto-malt/vimto-malt-univers-06-grains-v01.avif",
      "width": 1680,
      "height": 945
    }
  ]
} as const satisfies Record<string, readonly ProductUniverseStory[]>;

export const PRODUCT_UNIVERSE_SUPPORTING_STORIES = {
  "vimto-sparkling": [
    {
      "id": "vimto-bottle-lantern",
      "eyebrow": "L’original",
      "title": "Le goût historique en bouteille",
      "body": "La bouteille en verre prolonge la signature Vimto autour des tables et des moments de partage.",
      "alt": "Bouteilles Vimto encadrant une lanterne marocaine sur fond rouge.",
      "src": "/media/mpm/editorial/vimto-sparkling/vimto-bottle-lantern-v02.webp",
      "avif": "/media/mpm/editorial/vimto-sparkling/vimto-bottle-lantern-v02.avif",
      "width": 752,
      "height": 600
    },
    {
      "id": "vimto-bottle-serve",
      "eyebrow": "Le service",
      "title": "Servir très frais",
      "body": "Une bouteille, un verre rempli de glaçons et le rituel de service Vimto.",
      "alt": "Bouteille Vimto, pichet et verres remplis d’une boisson rouge avec glaçons.",
      "src": "/media/mpm/editorial/vimto-sparkling/vimto-bottle-serve.webp",
      "avif": "/media/mpm/editorial/vimto-sparkling/vimto-bottle-serve.avif",
      "width": 540,
      "height": 405
    },
    {
      "id": "vimto-bottle-original",
      "eyebrow": "L’iconique",
      "title": "Une présence reconnaissable",
      "body": "La bouteille originale installe Vimto dans un décor profond, entre héritage et fraîcheur.",
      "alt": "Bouteille Vimto originale accompagnée d’un verre servi et de fruits rouges.",
      "src": "/media/mpm/editorial/vimto-sparkling/vimto-bottle-original-v02.webp",
      "avif": "/media/mpm/editorial/vimto-sparkling/vimto-bottle-original-v02.avif",
      "width": 1440,
      "height": 1800
    },
    {
      "id": "vimto-bottle-signature",
      "eyebrow": "La signature",
      "title": "Une histoire qui se partage",
      "body": "Une expression de la gamme Vimto pensée pour les instants calmes comme les grandes tablées.",
      "alt": "Bouteille Vimto inclinée, fruits rouges et verre servi sur fond rouge.",
      "src": "/media/mpm/editorial/vimto-sparkling/vimto-bottle-signature.webp",
      "avif": "/media/mpm/editorial/vimto-sparkling/vimto-bottle-signature.avif",
      "width": 404,
      "height": 316
    }
  ]
} as const satisfies Record<string, readonly Omit<ProductUniverseStory, "order" | "layout" | "animation">[]>;

export function getProductUniverseStories(slug: string) {
  return PRODUCT_UNIVERSE_STORIES[slug as keyof typeof PRODUCT_UNIVERSE_STORIES] ?? [];
}

export function getProductUniverseSupportingStories(slug: string) {
  return PRODUCT_UNIVERSE_SUPPORTING_STORIES[slug as keyof typeof PRODUCT_UNIVERSE_SUPPORTING_STORIES] ?? [];
}
